version: '3'
services:
  prerender-server:
    image: prerender-server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - SYS_ADMIN
    environment:
      PORT: "3000"
  sitemap-generator:
    image: sitemap-generator
    ports:
      - "4000:4000"
    links:
      - antengo-graphql
    depends_on:
      - antengo-graphql
    environment:
      PORT: "4000"
      BASE_URL: ${BASE_URL:-https://sellwild.com}
      GRAPHQL: ${GRAPHQL:-http://antengo-graphql:5000}
      LOGGER: ${LOGGER:-debug}
  antengo-graphql:
    image: antengo-graphql
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      LOGGER: ${LOGGER:-debug}
      API_URL: ${API_URL:?err}
  prerender-agent:
    image: prerender-agent
    links:
      - prerender-server
      - sitemap-generator
    depends_on:
      - prerender-server
      - sitemap-generator
    environment:
      PORT: "8080"
      LOGGER: ${LOGGER:-debug}
      PUBLIC: ${PUBLIC_DIST:-/src/app/public}
      SITEMAP_URL: ${SITEMAP_URL:-http://sitemap-generator:4000}
      PRERENDER_URL: ${PRERENDER_URL:-http://prerender-server:3000}
      PRERENDER_TOKEN: ${PRERENDER_TOKEN}
    ports:
      - "80:8080"
    volumes:
      - ${PUBLIC_SRC:-./prerender-agent/public}:${PUBLIC_DIST:-/src/app/public}

