version: '3'
services:
  # prerender-server:
  #   build: ./prerender-server
  #   image: ${REGISTRY}prerender-server:${CIRCLE_SHA1:-latest}
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   cap_add:
  #     - SYS_ADMIN
  #   environment:
  #     PORT: "3000"
  # sitemap-generator:
  #   build: ./sitemap-generator
  #   image: ${REGISTRY}sitemap-generator:${CIRCLE_SHA1:-latest}
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - antengo-graphql
  #   depends_on:
  #     - antengo-graphql
  #   environment:
  #     PORT: "4000"
  #     BASE_URL: ${BASE_URL:-https://sellwild.com}
  #     GRAPHQL: ${GRAPHQL:-http://antengo-graphql:5000}
  #     LOGGER: ${LOGGER:-info}
  # antengo-graphql:
  #   build: ./antengo-graphql
  #   image: ${REGISTRY}antengo-graphql:${CIRCLE_SHA1:-latest}
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     PORT: "5000"
  #     LOGGER: ${LOGGER:-info}
  #     API_URL: ${API_URL:-https://api.antengo.com}
  prerender-agent:
    build: ./prerender-agent
    image: ${REGISTRY}prerender-agent:${CIRCLE_SHA1:-latest}
    # links:
    #   - prerender-server
    #   - sitemap-generator
    # depends_on:
    #   - prerender-server
    #   - sitemap-generator
    environment:
      PORT: "8080"
      LOGGER: ${LOGGER:-info}
      PUBLIC: ${PUBLIC_DIST:-/src/app/public}
      PRERENDER_URL: ${PRERENDER_URL:-http://prerender-server:3000}
      PRERENDER_TOKEN: ${PRERENDER_TOKEN}
    ports:
      - "80:8080"
    volumes:
      - ${PUBLIC_SRC:-./prerender-agent/public}:${PUBLIC_DIST:-/src/app/public}

