version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set convenience environment variables
          command: |
            echo 'export REGISTRY="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
      
      - run: docker-compose build

      - run: docker images --format="{{.Repository}}"

      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $(docker images --format="{{.Repository}}")

      - persist_to_workspace:
          root: .
          paths:
            - docker-image

  deploy:  
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Set convenience environment variables
          command: |
            echo 'export REGISTRY="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
            docker images --format="{{.Repository}}"
      - run:
          name: Push images
          command: |
            docker-compose push
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master