version: 2
jobs:
  build:

    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
    
      - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
        name: Setup remote docker
        command: setup_remote_docker

      - run:
        name: Checkout repo
        command: checkout

      - run:
        name: Build Images
        command: |
          REGISTRY=${REGISTRY} docker-compose push