version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Set convenience environment variables
          command: |
            echo 'export REGISTRY="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
      
      - run: docker-compose build

      - run: docker images docker images --format="{{.Repository}}"

      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $(docker images docker images --format="{{.Repository}}")

      - persist_to_workspace:
          root: .
          paths:
            - docker-image

  deploy:  
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - restore_cache:
          key: v1-{{ checksum "requirements.txt" }}
      - run:
          name: Set convenience environment variables
          command: |
            echo 'export REGISTRY="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
            docker images --format="{{.Repository}}"
      - run:
          name: Login
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - run:
          name: Push images
          command: |
            docker-compose push
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master